#!/bin/bash
# Create monolithic grub instead of the default one created by grub-install

set -e
# set -x

image=/boot/efi/EFI/debian/grubx64.efi
all_modules=$(basename -s .mod /usr/lib/grub/x86_64-efi/*.mod | tr '\n' ' ')

echo "Creating monolithic EFI image at $image"
grub-mkstandalone \
  --format=x86_64-efi \
  --output=$image \
  --locales="" \
  --fonts="" \
  --compress=xz \
  --modules="$all_modules" \
  "boot/grub/grub.cfg=/boot/efi/EFI/debian/grub.cfg" \
  "crypto-keyfile.img=/crypto-keyfile.img"


